name: D

on:
  push:
    branches-ignore:
      - travis-*
      - circleci-*
      - appveyor-*
      - dustmite-*
      - gh-pages

  pull_request:
    branches-ignore:
      - travis-*
      - circleci-*
      - appveyor-*
      - dustmite-*
      - gh-pages

jobs:
  build:
    name: 'Everything'
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        dc: [ dmd-latest, dmd-2.084.0, ldc-latest, ldc-1.14.0 ]
        exclude:
          - { os: macOS-latest, dc: dmd-2.084.0 }
          - { os: macOS-latest, dc: ldc-1.14.0 }

    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: 'Install D compiler'
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build and test'
      run: |
        dub test